name: Build and deploy ASP app to Azure Web App - studentdetialsweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -o ./published --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: ./published

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6B4CB7DE2F8D46619FF2B0225BB443C6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3183C3214EE343919DD49AE8406F6C55 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0AACA36311D64FABBBFE8280A295E1A5 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'studentdetialsweb'
          slot-name: 'Production'
          package: ./published
